### ISSUE TITLE
建议与疑问🤔

### ISSUE THREAD

**Issue by WyInnovate** [IAMSHENSH/g-mark-magic-ext#1]
# 环境
1. window11
2. edge 版本 120.0.2210.91 (正式版本) （64 位）
3. chrome 版本 120.0.6099.130 (正式版本) （64 位）
# 建议如下

## 搜索相关

1. 是否考虑搜索框输入内容可回车触发搜索？
4. 点击ByAdded按钮时，如果搜索框内有内容，应该进行筛选并排序，提了个PR（不懂JavaScript用gpt写了下，测试没问题）
5. 是否考虑搜索后点击Check按钮对搜索后的网页进行检查？

## 界面显示相关

1. 是否考虑多语言，比如中文、英文等的切换？
2. 是否增加切换到extension://ohlehijmfkkmigdcpdhpaghojfapfldc/sidepanel.html 展示的按钮？

# 疑问如下

1. ByUsed按钮旁边的三色按钮（绿、黄、红）是否只有在Check后点击才会起到筛选的作用？
2. 网页标签左侧的绿色底色代表什么？黑色圆点代表什么？

# 问题1如下
## 描述
目前存在安装MarkMagic后打开MarkMagic后列表无法加载的情况，看了下控制台错误提示为：
```
--> INIT SIDE PANEL
Uncaught (in promise) undefined
```
## 图例
![image](https://github.com/IAMSHENSH/g-mark-magic-ext/assets/40713819/1de803af-24ab-4f1b-9191-bb98a3e2f23f)
![image](https://github.com/IAMSHENSH/g-mark-magic-ext/assets/40713819/78506413-b968-4105-8f7a-2bfb598829ec)

## 排查并解决
经过排查发现是readLocalStorage中判断undefined的问题，提了PR

# 问题2如下
在有书签的情况下，目前存在点击Check按钮后报错的问题，该网站在浏览器中可正常打开，报错信息如下：
```
sidepanel.html:1  Access to fetch at 'https://mp.weixin.qq.com/s/8GXICY3ODuDA3SAHDlNySA' from origin 'chrome-extension://hfniapomagjkfonolfpcibicmemaakpf' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

---

感谢大佬的开发，我是从少数派上看到您的文章过来的，目前我的收藏夹有BookMarksNumber 1947，特别需要这样的一个浏览器扩展来帮助我筛选失效链接，再次感谢大佬

**Comment by IAMSHENSH** [comment]
Hi~ @s544838371 

非常感谢您提出的宝贵建议，对项目发展和改进有着重要的意义。您提及的多语言支持和搜索框回车触发搜索等功能，我在未来版本中确实考虑了这些改进，并会在计划中逐步实现，为用户提供更加便捷的体验。

关于过滤条件的交互，我们正在思考一个更完美的解决方案，以提升用户体验和功能的易用性。同时，也非常感谢您提供的关于 ByAdded 功能的 Pull Request，我会认真测试和审查，以便在下一个版本中融入这些优秀的功能。

针对您的疑问，三色按钮（绿、黄、红）代表筛选链接的不同状态，但需要完成网页状态检查后才能起到筛选作用，以便用户更清晰地了解链接状态。而网页标签左侧的灰色表示未检查的默认状态标识。

对于问题 1 和问题 2 中提到的问题，我已经确认并理解了情况。问题一中的本地存储读取错误已经得到您的 Pull Request 确认，并将在下一个版本中进行修复。同时，问题二中的跨域限制也是我的失误，我将在后续版本中对此进行修复。

再次感谢您的耐心反馈和宝贵建议。我会尽快发布下一个版本~ 🍻

**Comment by WyInnovate** [comment]
> Hi~ @s544838371
> 
> 非常感谢您提出的宝贵建议，对项目发展和改进有着重要的意义。您提及的多语言支持和搜索框回车触发搜索等功能，我在未来版本中确实考虑了这些改进，并会在计划中逐步实现，为用户提供更加便捷的体验。
> 
> 关于过滤条件的交互，我们正在思考一个更完美的解决方案，以提升用户体验和功能的易用性。同时，也非常感谢您提供的关于 ByAdded 功能的 Pull Request，我会认真测试和审查，以便在下一个版本中融入这些优秀的功能。
> 
> 针对您的疑问，三色按钮（绿、黄、红）代表筛选链接的不同状态，但需要完成网页状态检查后才能起到筛选作用，以便用户更清晰地了解链接状态。而网页标签左侧的灰色表示未检查的默认状态标识。
> 
> 对于问题 1 和问题 2 中提到的问题，我已经确认并理解了情况。问题一中的本地存储读取错误已经得到您的 Pull Request 确认，并将在下一个版本中进行修复。同时，问题二中的跨域限制也是我的失误，我将在后续版本中对此进行修复。
> 
> 再次感谢您的耐心反馈和宝贵建议。我会尽快发布下一个版本~ 🍻

收到，期待下一个版本

**Comment by IAMSHENSH** [comment]
解决问题的版本已经发布啦~ 观察到你使用的是 edge 浏览器， 可以[在这里直接安装](https://microsoftedge.microsoft.com/addons/detail/markmagic/chdnocboifbdehfnghinbjjcnklgdafm)啦。 🥰 @s544838371

**Comment by WyInnovate** [comment]
> 解决问题的版本已经发布啦~ 观察到你使用的是 edge 浏览器， 可以[在这里直接安装](https://microsoftedge.microsoft.com/addons/detail/markmagic/chdnocboifbdehfnghinbjjcnklgdafm)啦。 🥰 @s544838371

了解，昨天看到了版本更新，加油
